### ISSUE TITLE
sql文件有吗

### ISSUE THREAD

**Issue by LetLetMe** [realzhengyiming/MeiTuanMinSu_DataAnalysis#1]

**Comment by LetLetMe** [comment]
sql文件有吗

**Comment by realzhengyiming** [comment]
这个数据量好像还是有点大的，并且涉及到很多表，可能不太方便

**Comment by linhhubku** [comment]
您好，您这个是在mysql建了哪些表呀

**Comment by linhhubku** [comment]
方便加个QQ问您一下吗

**Comment by realzhengyiming** [comment]
@linhhubku 执行django的 migrate ，会自动建立好需要的所有表

**Comment by Nightglow12** [comment]
爬虫是不是不能用了，有sql文件吗（跪求）

**Comment by realzhengyiming** [comment]
爬虫应该是不能用了，sql文件找到一个，我看看怎么发给你方便一些
________________________________
发件人: Nightglow12 ***@***.***>
发送时间: 2023年5月31日 4:41
收件人: realzhengyiming/MeiTuanMinSu_DataAnalysis ***@***.***>
抄送: EM ***@***.***>; Comment ***@***.***>
主题: Re: [realzhengyiming/MeiTuanMinSu_DataAnalysis] sql文件有吗 (#1)


爬虫是不是不能用了，有sql文件吗（跪求）

―

**Comment by Nightglow12** [comment]
> 
用百度网盘，或者加一个您的联系方式可以嘛（谢谢！）

**Comment by realzhengyiming** [comment]
嗯，那加我qq
1403459511@qq.com
