### ISSUE TITLE
字体破解这个模块不行啊，不能下载woff文件到本地

### ISSUE THREAD

**Issue by guanxijing** [realzhengyiming/MeiTuanMinSu_DataAnalysis#2]
字体破解这个模块不行啊，不能下载woff文件到本地

**Comment by realzhengyiming** [comment]
已修复字体解密失效的问题

**Comment by guanxijing** [comment]
好的，谢谢大神，我去Github看看
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YiMing,Zheng"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 下午4:36
收件人: "realzhengyiming/MeiTuanMinSu_DataAnalysis"<MeiTuanMinSu_DataAnalysis@noreply.github.com&gt;; 
抄送: "那一夜"<729017304@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [realzhengyiming/MeiTuanMinSu_DataAnalysis] 字体破解这个模块不行啊，不能下载woff文件到本地 (#2)





 
已修复字体解密失效的问题
